export type SiteConfig = typeof siteConfig;

export const siteConfig = {
  name: "Nathan Roark",
  url: "https://nathanroark.dev",
  ogImage: "https://nathanroark.dev/og.png",
  description: "Full Stack Software Engineer",
  mainNav: [
    {
      title: "Home",
      href: "/",
    },
  ],
  links: {
    github: "https://github.com/nathanroark",
  },
  keywords: [
    "Nathan Roark",
    "Nathan",
    "Roark",
    "Software Engineer",
    "Full Stack Engineer",
    "Full Stack Developer",
    "Full Stack Software Engineer",
    "Full Stack Software Developer",
    "Frontend Engineer",
    "Embedded Engineer",
    "Embedded",
    "Embedded Systems",
    "Engineer",
    "Engineering",
    "Computer Science",
    "Computer Engineer",
    "UAH",
    "University of Alabama in Huntsville",
    "Telperion",
    "Web Development",
    "Software Development",
    "Modeling and Simulation",
    "M&S",
    "Aerospace",
    "Contractor",
    "Consultant",
    "Portfolio",
    "Resume",
    "CV",
    "Developer",
    "Programming",
    "Development",
    "Tech",
    "Technology",
    "Trideum",
    "C++",
    "AI",
    "Machine Learning",
  ],
};
