export const TechIcons: Record<string, string> = {
  // Languages
  TypeScript: "logos:typescript-icon",
  "C++": "logos:c-plusplus",
  Python: "logos:python",
  JavaScript: "logos:javascript",
  // Machine learning
  PyTorch: "logos:pytorch-icon",
  NumPy: "logos:numpy",
  Pandas: "local:pandas",
  "scikit-learn": "simple-icons:scikitlearn",
  SciPy: "simple-icons:scipy",
  Jupyter: "logos:jupyter",
  CNNs: "lucide:brain-circuit",
  RNNs: "lucide:repeat",
  "Transfer Learning": "lucide:brain",
  // Computer vision
  OpenCV: "simple-icons:opencv",
  "Object Detection": "lucide:scan-box",
  "Image Segmentation": "lucide:layers",
  YOLO: "simple-icons:ultralytics",
  ONNX: "simple-icons:onnx",
  TensorRT: "local:nvidia",
  CUDA: "local:nvidia",
  // Frameworks & libraries
  React: "logos:react",
  Astro: "local:astro",
  Svelte: "logos:svelte-icon",
  "Tanstack Start": "local:tanstack",
  "Next.js": "simple-icons:nextdotjs",
  Tailwind: "logos:tailwindcss-icon",
  Vite: "logos:vitejs",
  SvelteKit: "logos:svelte-icon",
  SASS: "logos:sass",
  "Styled Components": "simple-icons:styledcomponents",
  immer: "logos:immer-icon",
  Markdown: "simple-icons:markdown",
  FastAPI: "logos:fastapi-icon",
  Hono: "logos:hono",
  Prisma: "simple-icons:prisma",
  Qt: "logos:qt",
  D3: "logos:d3",
  Matplotlib: "logos:matplotlib-icon",
  Canvas: "lucide:frame",
  // Tools
  PostgreSQL: "logos:postgresql",
  Docker: "logos:docker-icon",
  Kubernetes: "logos:kubernetes",
  Git: "logos:git-icon",
  Unity: "simple-icons:unity",
  FPGA: "lucide:cpu",
  Verilog: "lucide:cpu",
  Unix: "lucide:terminal",
  Helm: "simple-icons:helm",
  Cloudflare: "logos:cloudflare-icon",
  Azure: "logos:microsoft-azure",
  // Protocols & APIs
  REST: "lucide:webhook",
  gRPC: "lucide:network",
  Websockets: "lucide:cable",
  XML: "lucide:code-xml",
  JSON: "simple-icons:json",
  Link16: "lucide:radio",
  JREAP: "lucide:radio-tower",
  VMF: "lucide:radio",
  DIS: "lucide:antenna",
  "MIL STD 1553": "lucide:circuit-board",
  "Signal Processing": "lucide:audio-waveform",
};
