export const FrameworkIcons: Record<string, string> = {
  React: "logos:react",
  Astro: "astro",
  Svelte: "logos:svelte-icon",
  "Tanstack Start": "tanstack",
  "Next.js": "simple-icons:nextdotjs",
  Tailwind: "logos:tailwindcss-icon",
  Vite: "logos:vitejs",
  SvelteKit: "logos:svelte-icon",
  SASS: "logos:sass",
  // "Styled Components": "simple-icons:styledcomponents",
  immer: "logos:immer-icon",
  Markdown: "simple-icons:markdown",
  FastAPI: "logos:fastapi-icon",
  Hono: "logos:hono",
  Prisma: "simple-icons:prisma",
  Qt: "logos:qt",
  D3: "logos:d3",
  Canvas: "lucide:frame",
};
